In [206]:
import math as m
from scipy import linalg
import numpy as np
import matplotlib.pyplot as plt

In [234]:
print('Enter max weight')
M = int(input())#max weight

Enter max weight
20


In [235]:
print('Enter number of types')
N = int(input())#number of types

Enter number of types
4


In [236]:
goods = np.array([[0]*(N+1),[0]*(N+1)])
goods[0][0], goods[1][0]
for i in range(1, N+1):
    print('Enter weight of', i, 'object')
    goods[0][i] = int(input())
    print('Enter price of', i, 'object')
    goods[1][i] = int(input())
goods

Enter weight of 1 object
2
Enter price of 1 object
10
Enter weight of 2 object
3
Enter price of 2 object
20
Enter weight of 3 object
4
Enter price of 3 object
30
Enter weight of 4 object
5
Enter price of 4 object
40


array([[ 0,  2,  3,  4,  5],
       [ 0, 10, 20, 30, 40]])

In [237]:
goods

array([[ 0,  2,  3,  4,  5],
       [ 0, 10, 20, 30, 40]])

### dp - двумерная динамика по количеству выбранных типов. Значения - максимальная стоимость для данной точки (кол-во типов, макс вес)

In [238]:
dp = np.array([[0]*(M+1)]*(N+1))
dp

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [239]:
for i in range(1, N+1):    #brute force of types 
    for w in range(1, M+1):     #w - available weight for i types
        dp[i][w] = dp[i-1][w]
        for x_i in range(0, w//goods[0][i] + 1):    #x_i-number of goods
            dp[i][w] = max(dp[i][w], dp[i-1][w-x_i*goods[0][i]] + goods[1][i]*x_i) #Bellman equation
            print(i, ' ', w, ' ', x_i,dp[i-1][w], ' ', dp[i-1][w-x_i*goods[0][i]] + goods[1][i]*x_i, dp[i][w])
        print()

1   1   0 0   0 0

1   2   0 0   0 0
1   2   1 0   10 10

1   3   0 0   0 0
1   3   1 0   10 10

1   4   0 0   0 0
1   4   1 0   10 10
1   4   2 0   20 20

1   5   0 0   0 0
1   5   1 0   10 10
1   5   2 0   20 20

1   6   0 0   0 0
1   6   1 0   10 10
1   6   2 0   20 20
1   6   3 0   30 30

1   7   0 0   0 0
1   7   1 0   10 10
1   7   2 0   20 20
1   7   3 0   30 30

1   8   0 0   0 0
1   8   1 0   10 10
1   8   2 0   20 20
1   8   3 0   30 30
1   8   4 0   40 40

1   9   0 0   0 0
1   9   1 0   10 10
1   9   2 0   20 20
1   9   3 0   30 30
1   9   4 0   40 40

1   10   0 0   0 0
1   10   1 0   10 10
1   10   2 0   20 20
1   10   3 0   30 30
1   10   4 0   40 40
1   10   5 0   50 50

1   11   0 0   0 0
1   11   1 0   10 10
1   11   2 0   20 20
1   11   3 0   30 30
1   11   4 0   40 40
1   11   5 0   50 50

1   12   0 0   0 0
1   12   1 0   10 10
1   12   2 0   20 20
1   12   3 0   30 30
1   12   4 0   40 40
1   12   5 0   50 50
1   12   6 0   60 60

1   13   0 0   0 0
1   13   1 0  

In [240]:
dp

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  10,  10,  20,  20,  30,  30,  40,  40,  50,  50,  60,
         60,  70,  70,  80,  80,  90,  90, 100],
       [  0,   0,  10,  20,  20,  30,  40,  40,  50,  60,  60,  70,  80,
         80,  90, 100, 100, 110, 120, 120, 130],
       [  0,   0,  10,  20,  30,  30,  40,  50,  60,  60,  70,  80,  90,
         90, 100, 110, 120, 120, 130, 140, 150],
       [  0,   0,  10,  20,  30,  40,  40,  50,  60,  70,  80,  80,  90,
        100, 110, 120, 120, 130, 140, 150, 160]])

### восстановление ответа

In [241]:
answer = np.array([0]*N)

In [242]:
def restore_answer(i, w):
    if  goods[1][i] != 0 and dp[N][M]/goods[1][i] == dp[N][M]//goods[1][i] and goods[1][i] != 0:
        answer[i-1] = dp[N][M]//goods[1][i]
        return 0
    elif dp[i][w] == 0:
        return 0
    elif dp[i][w] == dp[i-1][w]:
        print('*')
        restore_answer(i-1, w)
    else:
        x_i = (dp[i][w] - dp[i-1][w])//goods[1][i]
        restore_answer(i-1, w - goods[0][i]*x_i)
        answer[i-1] = x_i 